name: Black Formatting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
  
      - name: Install dependencies
        run: pip install black

      - name: Run linter
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          black: true
          auto_fix: true
          commit_message: 'Fixed code style with ${linter}'
          git_name: 'MarvinRHCS'
          git_email: 'marvin.rh.robot@gmail.com'